const mongoose = require('mongoose');

const schema = new mongoose.Schema({
  rev: { type: String, required: true },
  kind: [String],
  created: { type: Date, default: Date.now },
  libraryId: { type: String, required: true },
  creatorId: { type: String, required: true },
  description: String,
  classification: { type: String, required: true },
  type: { type: String, required: true },
  tags: [String],
  elements: {
    exchange_id: { elementType: String, value: String },
    facility_id: { elementType: String, value: String },
    city: { elementType: String, value: String },
    zipcode: { elementType: String, value: String },
    buildingNumber: { elementType: String, value: String },
    name: { elementType: String, value: String },
    source: { elementType: String, value: String },
    rejectionreason: { elementType: String, value: String },
    latitude: { elementType: String, value: String },
    state: { elementType: String, value: String },
    streetAddress: { elementType: String, value: String },
    description: { elementType: String, value: String },
    trainingHoliday: { elementType: String, value: String },
    thursdayHours: { elementType: String, value: String },
    longitude: { elementType: String, value: String },
    subcategory: { elementType: String, value: String },
    federalHoliday: { elementType: String, value: String },
    installation: { elementType: String, value: String },
    onlineOrderURL: { elementType: String, value: String },
    notice: { elementType: String, value: String },
    mondayHours: { elementType: String, value: String },
    parentCategory: { elementType: String, value: String },
    sundayHours: { elementType: String, value: String },
    primaryPhone: { elementType: String, value: String },
    websiteUrl: { elementType: String, value: String },
    category: { elementType: String, value: String },
    wednesdayHours: { elementType: String, value: String },
    installationid: { elementType: String, value: String },
    saturdayHours: { elementType: String, value: String },
    fridayHours: { elementType: String, value: String },
    thumbnailUrl: { elementType: String, value: String },
    tuesdayHours: { elementType: String, value: String },
  },
  name: { type: String, required: true },
  lastModifierId: { type: String, required: true },
  typeId: { type: String, required: true },
  links: {
    createDraft: { href: String },
    retire: { href: String },
    self: { href: String },
    type: { href: String },
  },
  id: { type: String, required: true },
  lastModified: { type: Date, default: Date.now },
  systemModified: { type: Date, default: Date.now },
  status: { type: String, required: true },
});

const MWRModel = mongoose.model('MWRModel', schema);

module.exports = MWRModel;
